adds device query info to debug session
rokucommunity/roku-debug pull request #130
Opened 2023-01-20 18:06 UTC by sethmaclean

This pull request offers changes for Fixes #121

2023-01-20 18:20 UTC, TwitchBronBron requested changes
Looks pretty good. just a few small changes.

2023-01-20 18:20 UTC, TwitchBronBron commented on src/debugSession/BrightScriptDebugSession.ts
> +// import { ThemeIcon } from 'vscode';
Can you remove these commented-out imports?

2023-01-20 18:20 UTC, TwitchBronBron commented on src/debugSession/BrightScriptDebugSession.ts
> +        // }
Remove this commented-out code

2023-04-25 14:55 UTC, MilapNaik commented on src/DeviceInfo.ts
> +    // Anything nre they might add that we do not know about
```suggestion
    // Anything new they might add that we do not know about
```

2023-04-25 17:21 UTC, TwitchBronBron approved these changes

2023-04-25 17:21 UTC, merged